{% set version = "7.0.8-9" %}

package:
  name: imagemagick
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/ImageMagick/ImageMagick/archive/{{ version }}.tar.gz
  sha256: b46e7f02d037d96c364496fdcdf0575230f9b2273c9155ffd512bb2eba93a7f8

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - bzip2 1.0.*
    - fftw
    - fontconfig 2.12.*
    - freetype 2.8.1
    - ghostscript
    - giflib 5.1.*
    - graphviz
    - jbig
    - jpeg 9*
    - libpng >=1.6.32,<1.6.35
    - libtiff >=4.0.8,<4.0.10
    - libwebp 0.5.*
    - libxml2 2.9.*
    - openjpeg 2.3.*
    - pango 1.40.*
    - perl
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - xorg-libxt
    - xz 5.2.*
    - zlib 1.2.11
  run:
    - bzip2 1.0.*
    - fftw
    - fontconfig 2.12.*
    - freetype 2.8.1
    - ghostscript
    - giflib 5.1.*
    - graphviz
    - jbig
    - jpeg 9*
    - libpng >=1.6.32,<1.6.35
    - libtiff >=4.0.8,<4.0.10
    - libwebp 0.5.*
    - libxml2 2.9.*
    - openjpeg 2.3.*
    - pango 1.40.*
    - perl
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - xorg-libxt
    - xz 5.2.*
    - zlib 1.2.11

test:
  commands:
    - convert -version
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.imagemagick.org/
  license: ImageMagick
  license_file: LICENSE
  summary: 'Software suite to create, edit, compose, or convert bitmap images.'

extra:
  recipe-maintainers:
    - ocefpaf
