{% set version = "7.1.1-40" %}
{% set build = 0 %}
{% if license_family == "agpl" %}
    {% set build = build + 100 %}
{% endif %}

package:
  name: imagemagick
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/ImageMagick/ImageMagick/archive/{{ version }}.tar.gz
  sha256: a6aba2cfd9c20c909614b332d8b91b389909e233041aa46d29db9e371c6f114a

build:
  number: {{ build }}
  string: {{ license_family }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  skip: true  # [win]

requirements:
  build:
    - make
    - gnuconfig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - make
    - bzip2
    - fftw
    - fontconfig
    - fonts-conda-forge
    - freetype
    - ghostscript  # [license_family=="agpl"]
    - giflib
    - graphviz
    - jbig
    - libheif
    - libjpeg-turbo
    - libpng
    - librsvg
    - libtiff
    - libwebp
    - libxml2
    - openjpeg
    - pango
    - perl *
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - xorg-libxt
    - xz
    - zlib
    - glib
  run:
    - bzip2
    - fftw
    - fontconfig
    - freetype
    - fonts-conda-forge
    - ghostscript
    - giflib
    - graphviz
    - jbig
    - libheif
    - libpng
    - librsvg
    - libtiff
    - libwebp
    - libxml2
    - openjpeg
    - pango
    - perl *
    - pkg-config
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - xorg-libxt
    - xz
    - zlib

test:
  commands:
    - magick --version
    - magick --version | grep -q gslib && exit 1 || exit 0
    - Magick++-config --cflags

about:
  home: http://www.imagemagick.org/
  license_file: LICENSE
  license: AGPL  # [license_family=="agpl"]
  license_family: AGPL  # [license_family=="agpl"]
  license: ImageMagick  # [license_family=="imagemagick"]
  license_family: Apache  # [license_family=="imagemagick"]
  summary: Software suite to create, edit, compose, or convert bitmap images.

extra:
  recipe-maintainers:
    - ocefpaf
    - halldc
