appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jRaAVFYXxZALfqNDqhnFxnHxJfXjnkHebhDzpfOvgcNDLBgzxUsklXLG7CmgNC4a0k1u6/a8Kvi6YGLRlgM99pY27XXBZfOncW29wSTeyNnP/xUpeFL4ZsDZyfBhRa8m1qZ4E91KOWSMWYXVQWytgPZ1ABy3SIRZvV9qYh0DQNjH3VAB34hFSMYAbSFbsB2Cjo9lnzZ2jcFW8UvC6wcGESRpSVyQqyBeQKXvti+eZg6D+8XsaBcBrL8+XkGBZgChPmYnjazhz/7Yh7eWxCP7sGG8n1RKFeOEPv822EGoS30rxkfEfOs5L+CGYq/QvkXahq9ywnrTnbyb9lFL8hznSgP/S75X4/UGuJBB8fMtIrditMUWKwRhuBYR0rhoVY/NOrYFoTH1bCEEMRLBwzi62W9mpzewBU6kJLKQ+Zx/8f7AU0z9WXBwg0hCyaQYx+DA4NKDzbcfjiPtvJkiWdkvhCmGbminCJEHuNqd59UiMN8GcqqxfVRIaZEnBQUNIVdwhX9tXkA8eUFAU+L+5Hlvgv2Ky0Nhtcou189netbV+30AV3oSyPR/RLSRmuuG04+lmcysNgA40NO5ya0oYcKOjGO9AuqI7exEejtUBqaBGoAfLyAgQYNOl5jrlJFw/wEe7A44ZJ+5LN09fgEezUGav608qNoRFXVjtqP7aoc75DQ=}
